### ISSUE TITLE
Add codeigntion as "Speaker Sponsor" under "Partners"

### ISSUE THREAD

**Issue by prathamesh-sonpatki** [deccanrubyconf/drbc-2015-redesign#6]

**Comment by prathamesh-sonpatki** [comment]
![codeignition-logo](https://cloud.githubusercontent.com/assets/621238/8762571/9f22c16e-2d9a-11e5-95a6-268436389c26.png)

**Comment by mechanicles** [comment]
@prathamesh-sonpatki Sent PR for this issue on #8
